### ISSUE TITLE
reinstallation problem

### ISSUE THREAD

**Issue by reedyd** [SitecorePowerShell/Console#310] opened 2015-03-03 20:03 UTC
* Sitecore.NET 7.2 (rev. 141226) 
* PSE 3.0

I suspected something was wrong with my PSE installation, so I tried to reinstall it with Sitecore Installation Wizard. It threw this error, and then churned indefinitely. Did I break something?

[NullReferenceException: Object reference not set to an instance of an object.]
   Cognifide.PowerShell.Core.Modules.ModuleManager.get_Modules() +184
   Cognifide.PowerShell.Core.Modules.ModuleManager.GetFeatureRoots(String featureName) +102
   Cognifide.PowerShell.Integrations.Pipelines.PipelineProcessor`1.Process(TPipelineArgs args) +133

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +92
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +108
   Sitecore.Pipelines.Processor.Invoke(PipelineArgs args) +281
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +223
   Sitecore.Pipelines.Pipeline.Resume() +38
   Sitecore.Pipelines.Pipeline.DoStart(PipelineArgs args) +115
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +169
   Sitecore.Pipelines.Pipeline.Start(String pipelineName, PipelineArgs args, Boolean atomic) +63
   Sitecore.Pipelines.Pipeline.Start(String pipelineName, PipelineArgs args) +46
   Sitecore.Web.Authentication.TicketManager.Login(Ticket ticket) +125
   Sitecore.Web.Authentication.TicketManager.Relogin(String ticketId, Boolean redirect) +320
   Sitecore.Web.Authentication.TicketManager.Relogin(String ticketId) +28
   Sitecore.Pipelines.HttpRequest.UserResolver.RestoreRememberedUser() +55
   Sitecore.Pipelines.HttpRequest.UserResolver.Process(HttpRequestArgs args) +171
   (Object , Object[] ) +59
   Sitecore.Pipelines.PipelineMethod.Invoke(Object[] parameters) +36
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +237
   Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +158
   Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +64
   Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args) +50
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +450
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +69

**Comment by AdamNaj** [comment] 2015-03-03 21:34
I suspect the SPE Module monitor (the class that monitors changes in the ```Script Library``` for the purpose of enumerating scripts for integration points) is getting in the way of the installation.

I wonder if you could try reinstalling SPE again after deleting the following 2 files from your Website folder:
- ```bin\Cognifide.PowerShell.dll```
- ```App_Config\Include\Cognifide.PowerShell.config```

**Comment by reedyd** [comment] 2015-03-03 21:57
yes, that made it install clean. thank you!

**Comment by AdamNaj** [comment] 2015-03-03 22:10
Fantastic, thanks for the report, we'll see into making sure it works as it should for the reinstall.

**Comment by AdamNaj** [comment] 2015-05-26 18:03
Reopening as it needs merging to 7

**Comment by AdamNaj** [comment] 2015-05-29 14:54
Merged by implementing Issue #350

**Closed by AdamNaj** 2015-05-29 14:54 UTC
Labels: bug, question

**Comment by rootix** [comment] 2015-06-25 10:33
Hi Adam

I experience the same issue while upgrading from 3.0 to 3.1 (Sitecore 7 package)

Applying the proposed solution by deleting the two files worked for me as well. Does this mean the issue is still present?

**Comment by AdamNaj** [comment] 2015-06-25 20:07
3.0 is the problem. I suspect that when you're installing 3.1 it's the still the 3.0 dll that is interfering. Once that is installed do subsequent "upgrades" cause this as well for you?
