### ISSUE TITLE
Powershell script is throwing error

### ISSUE THREAD

**Issue by iprateeksunny** [SitecorePowerShell/Console#1306] opened 2023-05-25 12:31 UTC
Expected Behavior
When we run Powershell script in Powershell ISE in Sitecore. Then it should generate the desired output/result.

Actual Behavior
In Sitecore 9.2 environment, when we are running Powershell script on PowerShell console. After some time, we are seeing one exception and script execution is failing.

Steps to Reproduce the Problem
We copy the script and open Powershell ISE and execute the script then after some time we see below error:

Exception of type: 'System.OutOfMemoryException' was thrown,
at Line: 60 Char: 21

And it is happening with every script.
Sitecore Version: 9.2
Powershell Version: 5.1

![image](https://github.com/SitecorePowerShell/Console/assets/132745621/da7dc36f-862d-4766-b3f9-c06b3792cd64)

The scope is global and we are expecting around 10000 items in the report generated from script. and below is the script with line number 60 where we are getting error:

![image](https://github.com/SitecorePowerShell/Console/assets/132745621/c06a5fbc-8d86-404c-b28b-0b7abece8259)

**Comment by michaellwest** [comment] 2023-05-25 12:52
This appears to be a duplicate of #1305. Is there a reason you opened a new issue?

**Closed** 2023-05-25 13:10 UTC
