### ISSUE TITLE
New Module creates module underneath currently open script

### ISSUE THREAD

**Issue by jst-cyr** [SitecorePowerShell/Console#703] opened 2016-09-14 15:33 UTC
With Sitecore 8.2 using SPE 4.1, I had the JSON export script open and was attempting to create a new module. The new module was then created underneath the JSON export script location in the Sitecore item tree.

<img width="585" alt="ise-when-creating-module" src="https://cloud.githubusercontent.com/assets/4146192/18518643/76615758-7a66-11e6-8915-67bb9572adbf.png">
<img width="756" alt="createdmodulelocation" src="https://cloud.githubusercontent.com/assets/4146192/18518644/7667e852-7a66-11e6-8e97-f5d429749233.png">

**Comment by AlexKasaku** [comment] 2016-09-14 16:54
Can confirm, I was able to reproduce this.

This only affects new modules created through ISE, if the Insert Option is used in the Content Editor then that still creates the module in the expected place.

**Comment by AlexKasaku** [comment] 2016-09-14 20:37
This is due to the Create Integration Points script (`/sitecore/system/Modules/PowerShell/Script Library/Platform/Development/Integration points/Create Integration Points`).

The script takes the current context path and confirms that it sits under the Library path, otherwise it uses the default path:

```
$moduleRootPath = (Get-Item .).ProviderPath

if(-not $moduleRootPath.StartsWith("master:\system\Modules\PowerShell\Script Library",[System.StringComparison]::OrdinalIgnoreCase)){
    $moduleRootPath = "master:\system\Modules\PowerShell\Script Library"
}
```

Because the context path in this instance is a script that's under that path, it's accepted.

As the only locations that scripts can be created are under the Script Level item or under a Module Folder, I've changed this `if` statement to just confirm if the context item is a Module Folder, and if it isn't it will use the default location.

@AdamNaj  - I'll raise as a pull-request rather than committing directly so you can confirm if you're happy with this approach.

**Comment by AlexKasaku** [comment] 2016-09-14 20:39
Pull request added #706

**Comment by michaellwest** [comment] 2016-09-14 21:29
Fantastic! Excellent service!

**Comment by AlexKasaku** [comment] 2016-09-26 19:19
Commit merged across.

**Closed by AlexKasaku** 2016-09-26 19:19 UTC
Labels: area-development-ui, bug
