### ISSUE TITLE
Get timeout by large package

### ISSUE THREAD

**Issue by bschluter** [SitecorePowerShell/Console#462] opened 2015-08-18 13:31 UTC
I have a problem with SPE. 

When I try to install a large package with the code below (small packages work), I get the timeout error below:

I already changed the execution timeout in the web.config, but that wasn't the solution. How can I resolve this timeout issue. hope you guys know how to solve this.

========******tmeout error************===========================================

Exception calling "ExecuteScriptBlock2" with "5" argument(s): "The operation has timed out"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\SPE\Invoke-RemoteScript.ps1:115 char:13
+             $response = $singleConnection.Proxy.ExecuteScriptBlock2($Username, $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

==============******code executed in powershel SPI************=======================
# The following example remotely executes a script in Sitecore using a reusable session.
$session = New-ScriptSession -Username $SCSiteUser -Password $SCSitepw -ConnectionUri $SCSiteUri 
Write-Output "$time - Connected to Sitecore server $env:computername on $SCSiteUri"

# Execute PowerShell script on remote server
Invoke-RemoteScript -Session $session -ScriptBlock {
$TDSPackagePath = "F:\dev\bbb\Website\sitecore\admin\Packages"
	$time = [datetime]::Now
	Write-Output "$time - Start installing TDS package tds_mainportal_master_templates."

#tds_mainportal_master_settings.update
#tds_mainportal_master_templates.update

    Install-UpdatePackage -Path "$TDSPackagePath\tds_mainportal_master_templates.update" -InstallMode Install -UpgradeAction Upgrade
	$time = [datetime]::Now
	Write-Output "$time - Finished installing TDS package

**Comment by michaellwest** [comment] 2015-08-18 16:13
I guess we would need to figure out how to run it as a job and then check the status of that job.

**Comment by michaellwest** [comment] 2015-08-18 16:47
@bschluter can I have you try something to change the timeout?

Open up the Invoke-RemoteScript.ps1 and add this line right after 94 where the New-WebServiceProxy command is called.

```powershell
$proxy.Timeout = 300000
```

If this fixes it then perhaps we can add a parameter to the command for specifying the timeout.

**Comment by bschluter** [comment] 2015-08-19 05:23
I tried the above, but unfortunately this didn't solved the issue.

**Comment by AdamNaj** [comment] 2015-08-19 06:50
Hi @bschluter,

I realise that this is a problem that should be solved in the platform and raised the issue #463 to work around it properly. The timeout increase is a good workaround for now and you might try to increase it further as Michael suggested but it indeed is a workaround and you might want to enable your script to do something else instead of waiting idle for the package import to finish.

I'll look into it this week when I'm back home.

**Comment by AdamNaj** [comment] 2015-08-23 20:06
This is now fixed by Issue #463 - you can spin up an asynchronous background ScriptSession and call the server periodically to check whether it's ```State``` is still  ```Busy```. Once it finishes and it's state changes to ```Available``` you can ```Receive-ScriptSession``` to gather results from it or just ```Remove-ScriptSession``` if you don't need the results and signal to the user that the package is installed.

**Closed by AdamNaj** 2015-08-23 20:06 UTC

**Comment by ronaldvanvoorthuizen** [comment] 2015-08-25 08:01
Dear AdamNaj,
Good to hear you developed a fix.
Is it possible to give an indication of the release date of 3.3, including this fix?

Thanks,
Ronald

**Comment by AdamNaj** [comment] 2015-08-25 14:32
The original plan was to have it released at the end of the month. It hugely depends on our evening free time so I cannot really give you any assurance as to whether we will be able to keep that date exactly or whether it might slip by a week. I'll keep in mind though that you guys are waiting for it.

**Comment by ronaldvanvoorthuizen** [comment] 2015-08-26 09:24
Alright, thanks for the heads up!

**Comment by GlennvG** [comment] 2015-09-07 08:57
Hi @AdamNaj,

We are trying to update to 3.3. But the .zip download "Remoting for SPE 3.3" in de the Sitecore marketplace is empty. 

One extra question, do we also need to change our powershell script to fix this issue? Or can we keep it like the description voor @bschluter? 

Thanks!

**Comment by AdamNaj** [comment] 2015-09-07 10:28
I'll investigate the problem with the remoting, but in the mean time - if you don't need the functionality to download large files, you're fine with the remoting from 3.2.

As to the change of script, you will need to take advantage of the new functionality delivered as part of Issue #463 and ```Start-ScriptSession``` that installs your package this way. Then you can monitor the ```ScriptSession``` using the ```Get-ScriptSession``` as shown in [this YouTube tutorial](https://www.youtube.com/watch?v=zNyVrj1vH6c) - polling the result periodically untill your ```ScriptSession``` changes its state from ```Busy``` to ```Available``` at which point you can ```Remove-ScriptSession``` it and you're done - no timeouts this time :).

**Comment by AdamNaj** [comment] 2015-09-07 10:35
I've uploaded the new SPE Remoting 3.3 package. @michaellwest - you might want to investigate why the package didn't contain the module files when it was created by our distribution scripts.

**Comment by GlennvG** [comment] 2015-09-07 11:24
Hi Adam,

We are still having the timeout issue. Can you maybe tell us if we are missing something?

--------------------------------------------------------------------------
This is the script:

$session = Start-ScriptSession -Username $SCSiteUser -Password $SCSitepw -ConnectionUri $SCSiteUri -ScriptBlock {
$TDSPackagePath = "#{WebsiteInstallationPath}\sitecore\admin\Packages"
    Install-UpdatePackage -Path "$TDSPackagePath\tds_mainportal_master_templates.update" -InstallMode Install -UpgradeAction Upgrade
}

Wait-ScriptSession -Session $session | Out-Null

Receive-ScriptSession -Session $session

-----------------------------------------------------------------------------

And this the error:


Invoke-RemoteScript : Exception calling "ExecuteScriptBlock2" with "5" argument(s): "The operation has timed out"
At C:\Octopus\Work\20150907111649-692\Script.ps1:15 char:1
+ Invoke-RemoteScript -Session $session -ScriptBlock {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RemoteScript], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Invoke-RemoteScript

The remote script failed with exit code 1

**Comment by AdamNaj** [comment] 2015-09-07 12:42
The way you structured the script unfortunately is the cause why the situation has not improved for you.

What you need to do is have 2 distinct calls, one that initializes the installation like:

```powershell
$session = Start-ScriptSession -Username $SCSiteUser -Password $SCSitepw -ConnectionUri $SCSiteUri -ScriptBlock {
$TDSPackagePath = "#{WebsiteInstallationPath}\sitecore\admin\Packages"
Install-UpdatePackage -Path "$TDSPackagePath\tds_mainportal_master_templates.update" -InstallMode Install -UpgradeAction Upgrade
}
$session.ID
```
which results in you getting the handle to the script session executing the installation and then in your local script periodically (maybe once every 5 seconds?) call something like:

```powershell
(Get-ScriptSession -ID $id).State
```
Where the ```$id``` is the ID of the ```ScriptSession```that you got from the first execution and returns the State - either ```Busy``` or ```Available```. When the state flicks from ```Busy``` to ```Available``` - it means your package is installed.

**Comment by michaellwest** [comment] 2015-09-07 16:14
This is probably a more complete example to what you are looking for.

```powershell
Import-Module -Name SPE

$SCSiteUser = "admin"
$SCSitepw = "b"
$SCSiteUri = "http://console"

$session = New-ScriptSession -Username $SCSiteUser -Password $SCSitepw -ConnectionUri $SCSiteUri

$job = Invoke-RemoteScript -Session $session -ScriptBlock {
    Start-ScriptSession -ScriptBlock {
        # Replace the contents of this scriptblock with your installation steps. 
        # I just put $true there so something would come back.
        $true
    }
}

Invoke-RemoteScript -Session $session -ScriptBlock {
    $scriptSession = Get-ScriptSession -Id $params.JobId
    if($scriptSession.State -ne "Busy") {
        $scriptSession | Receive-ScriptSession
    }
} -Arguments @{"JobId" = $job.ID}
```

**Comment by GlennvG** [comment] 2015-09-08 08:01
@michaellwest thanks for the code!

We are using this as a step in our deployment. I included all the code in 1 step.

I'm sorry for so many questions. My powershell knowledge is not that high, but due to vacations of colleagues I need to fix this. Hope you can help me. Think we are almost there.

This results in the following error:
--------------------------------------------------------------------------------------------

Executing script on tentacle 'Caesar-Dux-OT'

Invoke-RemoteScript : Exception calling "ExecuteScriptBlock2" with "5" argument(s): "System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at Cognifide.PowerShell.Core.Host.ScriptSession.<>c.<ExecuteCommand>b__84_0(PSObject p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__aa`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Cognifide.PowerShell.Core.Host.ScriptSession.ExecuteCommand(Boolean stringOutput, Boolean internalScript, Boolean marshallResults)
   at Cognifide.PowerShell.Core.Host.ScriptSession.<>c__DisplayClass81_0.<ExecuteScriptPart>b__0()
   at Cognifide.PowerShell.Core.Utility.SpeTimer.Measure[T](String message, Func`1 action)
   at Cognifide.PowerShell.Core.Host.ScriptSession.ExecuteScriptPart(String script, Boolean stringOutput, Boolean internalScript, Boolean marshalResults)
   at Cognifide.PowerShell.Console.Services.RemoteAutomation.ExecuteScriptBlock inSite2(String userName, String password, String script, String cliXmlArgs, String siteName, String sessionId)
   at Cognifide.PowerShell.Console.Services.RemoteAutomation.ExecuteScriptBlock2(String userName, String password, String script, String cliXmlArgs, String sessionId)

   --- End of inner exception stack trace ---"

At C:\Octopus\Work\20150908074323-873\Script.ps1:19 char:1

+ Invoke-RemoteScript -Session $session -ScriptBlock {

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RemoteScript], MethodInvocationException

    + FullyQualifiedErrorId : SoapException,Invoke-RemoteScript

The remote script failed with exit code 1

**Comment by GlennvG** [comment] 2015-09-08 08:27
It looks like the first part of the script is working when I remove the busy check. So the update package is getting installed.

So whats left is to poll if the ScriptSession is Available. Hope you can help me with that. Until now still getting the above error.

**Comment by michaellwest** [comment] 2015-09-08 11:16
Hey @GlennvG , how about this updated example?

```powershell
$job = Invoke-RemoteScript -Session $session -ScriptBlock {
    Start-ScriptSession -ScriptBlock {
        # Replace the contents of this scriptblock with your installation steps. 
        # I just put $true there so something would come back.
        Start-Sleep -Seconds 10
        [PSCustomObject]@{"IsComplete"=$true}
    }
}

$keepRunning = $true
while($keepRunning) {
    $done = Invoke-RemoteScript -Session $session -ScriptBlock {
        $scriptSession = Get-ScriptSession -Id $params.JobId
        $scriptSession.State -ne "Busy"
    } -Arguments @{"JobId" = $job.ID} 

    if($done) {
        $keepRunning = $false

        Invoke-RemoteScript -Session $session -ScriptBlock {
            $scriptSession = Get-ScriptSession -Id $params.JobId
            if($scriptSession.State -ne "Busy") {
                $scriptSession | Receive-ScriptSession
            }
        } -Arguments @{"JobId" = $job.ID}    
    } else {
        Start-Sleep -Milliseconds 500
    }
}
```

I've added this to the book for reference.
http://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/remoting.html

**Comment by GlennvG** [comment] 2015-09-08 11:46
@michaellwest thanks for the example and reference. But this still gives me the same NullReferenceException as before.

on this line: "Invoke-RemoteScript -Session $session -ScriptBlock {" in this block:

 if($done) {
        $keepRunning = $false

        Invoke-RemoteScript -Session $session -ScriptBlock {
            $scriptSession = Get-ScriptSession -Id $params.JobId
            if($scriptSession.State -ne "Busy") {
                $scriptSession | Receive-ScriptSession
            }
        } -Arguments @{"JobId" = $job.ID}    
    } else {
        Start-Sleep -Milliseconds 500
    }

**Comment by michaellwest** [comment] 2015-09-08 12:26
@GlennvG I would like for you to perform tests inside of Sitecore (without remoting) to see exactly where the script is breaking.

Open up the SPE ISE (the one inside of Sitecore) and run the following:

```powershell
Get-ScriptSession
```

Then run it with a specific Job Id

```powershell
Get-ScriptSession -Id ...
```

Then keep going until you see that it works as you expect. I have a feeling this will help us pinpoint the problem better than through remoting.

**Comment by GlennvG** [comment] 2015-09-08 12:52
@michaellwest I think I already got it to work. Remove the last Invoke-RemoteScript, because then I know the script is finished right? Or do I need to open it again?

It seems like my deployment is running correct this time.

------------------------------------------------------------------------------------------

$job = Invoke-RemoteScript -Session $session -ScriptBlock {
    Start-ScriptSession -ScriptBlock {
        # Replace the contents of this scriptblock with your installation steps. 
        # I just put $true there so something would come back.
        Start-Sleep -Seconds 10
        [PSCustomObject]@{"IsComplete"=$true}
    }
}

$keepRunning = $true
while($keepRunning) {
    $done = Invoke-RemoteScript -Session $session -ScriptBlock {
        $scriptSession = Get-ScriptSession -Id $params.JobId
        $scriptSession.State -ne "Busy"
    } -Arguments @{"JobId" = $job.ID} 

    if($done) {
        $keepRunning = $false

         #script is done here, so no need to invoke-remotescript again??  

    } else {
        Start-Sleep -Milliseconds 500
    }
}

**Comment by michaellwest** [comment] 2015-09-08 13:07
In the example I provided, it does some rudimentary decisions on whether to keep going or not. There is a risk that the look keeps going because the job isn't found. I think if you are getting the first call to install the module and that works as you expect, then can find some time later to figure out why the status check isn't working for you.

**Comment by GlennvG** [comment] 2015-09-08 13:12
Yes it works now as expected. Thanks for the support :)!!

**Comment by onkarbhave17** [comment] 2016-01-22 15:27
I am getting same error while executing the script in bamboo. in this case it has series of tasks. uploading package is last one. Its giving the able error and not installing sitecore package. but when I am executing the script task alone without any previous tasks then it installs sitecore package but gives another error.
---------------------
Get-ScriptSession : The script session with Id 'System.String[]' cannot be found
---------------------

**Comment by AdamNaj** [comment] 2016-01-22 19:40
@onkarbhave17 the long time running sessions will be much easier to deal with once 4.0 is out which is about a week or so away. You will not need to deal with `Start-ScriptSession` explicitly but will be able to do the `Invoke-RemoteScript ... -AsJob` hang on there! :)

**Comment by onkarbhave17** [comment] 2016-01-23 21:23
Okay. thanks for update. :) ..it's bit urgent so I just found that in 1st case(as a series of steps)  variable "$done" immediately returns true and task ends with success. whereas job keeps running in sitecore and installs package.

**Comment by michaellwest** [comment] 2016-01-23 22:38
@onkarbhave17 Just be sure that your script does not have the following in it:

```powershell
Start-Sleep -Seconds 10
[PSCustomObject]@{"IsComplete"=$true}
```

**Comment by onkarbhave17** [comment] 2016-01-24 00:03
@michaellwest Removed the above mentioned block still getting the same issue. If I run only that script task in series of tasks then it works fine.

**Comment by onkarbhave17** [comment] 2016-01-24 21:58
I got it working after adding delay between Starting the job and checking status of it :)
