### ISSUE TITLE
get-childitem : Method not found:

### ISSUE THREAD

**Issue by a3codeDA** [SitecorePowerShell/Console#832] opened 2017-02-15 16:05 UTC
Hi I am try to get some child items at version Sitecore PowerShell Extensions-4.4 , 

`function Get-MediaItemWithNoReference {
    $items = get-childitem -Path "master:\sitecore\media library\Img" -Recurse | Where-Object { $_.TemplateID -ne [Sitecore.TemplateIDs]::MediaFolder }
    <#  Get-Item master: -Query "/sitecore/media library/Img//*" 
    #>
    
    foreach($item in $items) {
        if(!(HasReference($item))) {
            $item
        }
    }
}`

but I see an error like:

> get-childitem : Method not found: 'Void 

> System.Management.Automation.Provider.ContainerCmdletProvider.GetChildItems(System.String, Boolean, UInt32)'.
> At line:25 char:14
> +     $items = get-childitem -Path "master:\sitecore\media library\Img" -Recurse | ...
> +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], MissingMethodException
>     + FullyQualifiedErrorId : System.MissingMethodException,Microsoft.PowerShell.Commands.GetChildItemCommand

What is wrong ? at old version -2.7.5 it wasn't any issue

**Comment by AdamNaj** [comment] 2017-02-15 17:12
The problem is addressed by issue #827 and I've already fixed it in 4.4.1 release.
https://github.com/SitecorePowerShell/Console/releases/tag/4.4.1

The release is not yet on Marketplace but you can download the new packages from the link above.
Alternatively you can upgrade your Windows Management Framework to version 5.x, as using the newer framework APIs is what's caused it.

**Closed by AdamNaj** 2017-02-15 17:12 UTC
Labels: bug, response-duplicate, response-obsolete-windows-powershell
