### ISSUE TITLE
Upgrade Issue on Sitecore 7.2 already had powershell 4.0

### ISSUE THREAD

**Issue by mikesmith025** [SitecorePowerShell/Console#767] opened 2016-12-20 22:22 UTC
When attempting to install 4.3 package I get an error. I have sitecore 7.2 and already had powershell ext 4.0 installed. When attempting to install 4.3 package, I receive error :  Could not load type 'Sitecore.Data.Events.PublishCompletedRemoteEventArgs' from assembly 'Sitecore.Kernel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by tomunderhill** [comment] 2017-01-04 16:56
also have encountered this issue installing 4.3

**Comment by AdamNaj** [comment] 2017-01-05 08:38
I believe it's caused by a rogue config file in the package. if you could delete the `\files\App_Config\Include\Cognifide.PowerShell.Events.config` from inside of the inner zip, it should install fine. 

Thanks for reporting this!

**Comment by AdamNaj** [comment] 2017-01-10 16:49
Fixed on the local build environment

**Closed by AdamNaj** 2017-01-10 16:49 UTC
Labels: bug, bug-regression, impact-limited-sitecore-7
