### ISSUE TITLE
ISE and Console Style Settings Enhancements

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#416] opened 2015-07-18 04:56 UTC
The ISE script pane and Console pane should be user settings aware when it comes to styles for output streams.

Example:
I would like to configure the error background color to be red and the error forground white.

Before:
![image](https://cloud.githubusercontent.com/assets/933163/8760399/f2aff764-2cde-11e5-8bdf-5ac793f3f926.png)

After:
![image](https://cloud.githubusercontent.com/assets/933163/8760402/2e17bc6a-2cdf-11e5-8f3b-f2f8fe13d2c5.png)

Changes:
* [ ] Output stream colors

**Comment by AdamNaj** [comment] 2016-02-10 11:39
This is almost a duplicate of #565. Those colors cannot be persisted but I don't think the effort for building the UI would be worth it.

**Closed by AdamNaj** 2016-02-10 11:39 UTC
Labels: area-user-interface, improvement
