### ISSUE TITLE
Find-Item throwing error when Criteria parameter is used.

### ISSUE THREAD

**Issue by StefanTBG** [SitecorePowerShell/Console#501] opened 2015-09-18 20:54 UTC
In versions 3.1 and 3.3 for Sitecore 7, `Find-Item` throws an exception whenever the `Criteria` parameter is used.

For example:
```PowerShell
Find-Item -Index sitecore_master_index -Criteria @{Filter = "DescendantOf"; Field = $item} |
    Show-ListView -Property Name, @{Label="URL"; Expression={$_.Paths.FullPath}}
```

Throws the following exception:
> Find-Item : Cannot bind parameter 'Criteria'. Cannot convert the "System.Collections.Hashtable" value of type "System.Collections.Hashtable" to type "Cognifide.PowerShell.Commandlets.Data.Search.SearchCriteria".
At line:2 char:53
+ Find-Item -Index sitecore_master_index -Criteria <<<<  @{Filter = "DescendantOf"; Field = $item} |
    + CategoryInfo          : InvalidArgument: (:) [Find-Item], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Cognifide.PowerShell.Commandlets.Data.Search.FindItemCommand

We're currently seeing this happening in two seprate instances of Sitecore 7.2 using PowerShell Extensions 3.1 for Sitecore 7 and Extensions 3.3 for Sitecore 7.

**Comment by michaellwest** [comment] 2015-09-19 15:34
My first test with an existing install of SPE 3.1, then upgraded to 3.3 resulted in no issue. Now testing a fresh install.

**Comment by michaellwest** [comment] 2015-09-19 15:47
Installed a fresh instance of SPE 3.3 on a fresh instance of Sitecore 7.2 through SIM. I was able to run this without errors.

```powershell
$item = Get-Item -Path master:\content\home
Find-Item -Index sitecore_master_index -Criteria @{Filter = "DescendantOf"; Field = $item} |
    Show-ListView -Property Name, @{Label="URL"; Expression={$_.Paths.FullPath}}
```

If you are upgrading from a previous version of SPE, then perhaps some of the files are not overwritten.

@StefanTBG  Can you test out with a clean install to confirm one way or the other?

**Comment by AdamNaj** [comment] 2015-09-21 16:29
Based on the error message (and the fact that the above worked for me on Sitecore 7 with SPE 3.3) I have a suspicion the problem does not lie in SPE itself but possibly in the version of PowerShell. The ```-Criteria``` parameter as shown in the message is expecting the ```Cognifide.PowerShell.Commandlets.Data.Search.SearchCriteria``` type while we are really providing a ```Hashtable``` as the input. The latest versions of PowerShell deals with the fact no problem instantiating the ```SearchCriteria``` struct as needed, but I wonder if that is the case in potentially older version of PowerShell you might be using. You can type ```Get-Host``` to find out the version installed.

![image](https://cloud.githubusercontent.com/assets/1209953/9997825/896a7dd6-608e-11e5-8d62-1672baf7d7ee.png)

Would you be willing to install The latest version of Windows Management Framework (WMF) in an attempt to remedy the problem? If your indicated version of Windows PowerShell is 2.0 - it might be the cause of the problem. I would suggest that you update to at least version 3 or even better 4.

**Comment by StefanTBG** [comment] 2015-10-01 21:03
Hey @AdamNaj, it looks like that's what the issue was. After updating the PowerShell on each server the command runs as expected.

Thanks for the help!

**Comment by AdamNaj** [comment] 2015-10-04 22:00
Lovely! I'm closing the issue then, as solved  :)

**Closed by AdamNaj** 2015-10-04 22:00 UTC
Labels: cannot-reproduce, question
