### ISSUE TITLE
Close-Window prevents job from finishing when run outside ISE

### ISSUE THREAD

**Issue by jomiham** [SitecorePowerShell/Console#653] opened 2016-06-15 14:41 UTC
Hi,

We have a number of reports that uses Show-ListView to present the findings. In order to close the script dialog, we use Close-Window (like in the _Authoring Instrumentation/Content Editor/Context Menu/Author Statistics_ report).

When running a report from the context menu however, the job thread never finishes and eventually no more scripts can be run.

Easiest way to reproduce is to check the Rocks Job Viewer and run the _Author Statistics_ report via the context menu (may need to be enabled first) or create a new minimal context menu script, such as:

```powershell
sleep 1
Close-Window
```

Note that the jobs finish fine when running the scripts from within the ISE (comes up as UI instead of PowerShellRunner in the JobViewer). 

Kind Regards,
Jonas Hamnered

**Comment by AdamNaj** [comment] 2016-10-19 13:53
I wonder which version this was on and whether you are still experiencing this behaviour. A couple of versions ago I've changed the behaviour of Close-Window so that the runner closes itself rather than forcing the close from the job.

**Comment by jomiham** [comment] 2016-10-20 09:33
I'm seeing the issue now in PSE 4.1 running on Sitecore 8.1 both Update 1 and 3.

Is it not reproducible in your end?

**Comment by AdamNaj** [comment] 2016-10-20 11:10
Unfortunately I'm not 100% sure how to reproduce it. If you could provide a list of steps with Expected vs Actual Results - that would make it much easier for me to address it.
Maybe export and upload an SPE module that experiences the issue?

**Comment by jomiham** [comment] 2016-10-20 12:39
**Steps to reproduce**

The attached package contains a PSE Module with two Toolbox scripts:
[SPE Issue 653.zip](https://github.com/SitecorePowerShell/Console/files/541681/SPE.Issue.653.zip)

**Sleep**
```powershell
sleep 10
```

**Sleep and close**
```powershell
sleep 10
Close-Window
```

**In Sitecore 8.1 Update-3 with SPE 4.1:**
0. Connect with **Sitecore Rocks** and open **Job Viewer** 
1. In Sitecore Desktop mode, Install the attached package (contains the script module **"SPE Issue 653"** with the two scripts)
2. From the _Start > PowerShell Toolbox_ menu, run the **"Sleep"** script
3. In the **Job Viewer**: Note the **PowerShellRunner** job with status **"Running"**
4. After 10 seconds, close the PSE dialogue window
5. In the **Job Viewer**: Note that the **PowerShellRunner** job finishes and eventually disappears from the list (as expected)
6. From the _Start > PowerShell Toolbox_ menu, run the **"Sleep and close"** script
7. In the Job Viewer: Note the **PowerShellRunner** job with status **"Running"**
8. Note that the PSE dialogue automatically closes after 10 seconds
9. Check the **Job Viewer**
 
**Expected behaviour:**
PowerShellRunner job should finish

**Actual results**
PowerShellRunner job never finishes

Running the script again will create a new job that never finishes etc.

Note that running the scripts from the ISE does not have this issue (probably since there is no window to close).

Let me know if you need anything else!

**Comment by AdamNaj** [comment] 2016-10-23 19:42
This is awesome @jomiham!
Thank you very much for the detailed and well reproducible report!

I've been able to trace the cause to the final message that I was waiting to get confirmation from the dialog that was closed as part of the previous message.

This is now fixed. Thank you again for the great report and paying attention to the details :)

**Closed by AdamNaj** 2016-10-23 19:42 UTC
Labels: area-platform, area-user-interface, bug

**Comment by jomiham** [comment] 2016-10-25 21:56
Happy to help..! :-)
