### ISSUE TITLE
Console Does Not Load

### ISSUE THREAD

**Issue by NDurham12** [SitecorePowerShell/Console#352] opened 2015-05-29 04:52 UTC
Hey Guys, 

I know I've been quiet, I've just been working hard on a new project.  I've already installed SPE and needed some help in understanding why my laptop will not load the SPE Console.  The ISE Runs fine, but when ever I try to open the console, I get the rotating gears just rotate forever.  Is there a permission I'm missing?

Here's a screen cast.  I've already set the ExecutionPolicy to RemoteSigned. 

Name             : Sitecore Console Host 3.0.0.20644 on Windows PowerShell 3.0
Version          : 3.0.0.20644
InstanceId       : 3b431932-0be3-4d8d-a3f7-c61eb3aa3a2b
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Cognifide.PowerShell.Core.Host.ScriptingHostPrivateData
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

http://www.screencast.com/t/mNOVOd4n

**Comment by AdamNaj** [comment] 2015-05-29 10:05
Are you using Insite on your instance? There is a blog dealing with this problem although it should no longer affect SPE 3.0.

Can you look into the Chrome Dev tools and see if there is any error showing there?

**Comment by NDurham12** [comment] 2015-05-31 08:11
Hey there Adam. 

No I don't have Insite, even so, I tried the fix in the link.  Still getting the same problem.  

The JS error is actually a 500 error. 
![image](https://cloud.githubusercontent.com/assets/5875789/7901213/53b09252-0742-11e5-8296-ced4961fecf8.png)

I even installed SPE on my base sitecore site (that has nothing) and I get the same error there.  Other developers on my team don't have this issue, so it could be something related to my laptop.

Fiddler Results on 500 error: 
POST http://debcomlocalcm/sitecore%20modules/PowerShell/Services/PowerShellWebService.asmx/ExecuteCommand HTTP/1.1
Host: debcomlocalcm
Connection: keep-alive
Content-Length: 96
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://debcomlocalcm
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Content-Type: application/json; charset=UTF-8
Referer: http://debcomlocalcm/sitecore/shell/Applications/PowerShell/PowerShell-Console?sc_content=core
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: SC_ANALYTICS_GLOBAL_COOKIE=90d3982bb050420183969dd4ac82b1ed; sitecore_webedit_activestrip=Ribbon_Strip_ViewStrip; sitecore_webedit_ribbon=1; scContentEditorFoldersWidth=371; ASP.NET_SessionId=vktwjbj5bcooenghaoqfzenf; sc_fv=17.0.0; shell#lang=en; directenergybusiness#sc_mode=edit; __RequestVerificationToken=VzFLooLmRX4hn0AUX62ETKYf_u_S7KwYWPfC7JrJVpg9LjVPgth9LsfuuVDQwtaCdkcjNOBIhyEhIK4XKu88h4ROmnILUbRgPJRboYApehs1; .ASPXAUTH=6B925091362DEF7B558D3B33F83D705F12B4705B61D47110B438376048BFDC35CBA1744FF2E55CD80F8324710A061CAD040C8B2B627F5F64DEFE8BD85AB6990F8F32581AB186BEB7C211294415B84B44EC1B081479E71BBE8BB8E5767F71F1101034743929D6C387A51008085AA0CA6838DBE9ECCD83DE31F86F40B745A5AA1A63454E5CE8EE95A09ECD142E4FB1DE7D; sitecore_userticket=C7CBA97C2E4B491BAF4A453D30A7A08C; sc_rte_shuser=7C603B01CB1E531C885503CA4E2859E4227F4D5C14C1F697B5CF4774F14195AE30A3380DA336CB7629FDBF6A76BCD1C52BBEF257AECD2D1916190A2984952132011A1061D312D0840AB2AA8C342DA8BA8FE34D61245BAC684778D542E9BBFD6D3225F569ED8AE8CE310588F95B42574184453B62BD164E40FCCA88911E0A2F9B6B5A90F7D93A1FCF7DED593104521666; DEBPostalCode=Country=-&Region=-&City=-&ZipCode=-&Latitude=0.000000&Longitude=0.000000; __CSRFCOOKIE=7c5314ca-c502-4a15-b3fb-f9b916a18ceb

{"guid":"7224ea65-74cc-3824-179a-4f9e70622c03","command":"cd master:\\","stringFormat":"jsterm"}

**Comment by AdamNaj** [comment] 2015-06-23 10:21
Hi Nona,

Did you have any progress with this? I wasn't able to reproduce it in any way here.

**Comment by AdamNaj** [comment] 2015-07-29 20:12
Since this is a problem from 3.0 and we're nearing 3.2 I'll close this for the moment and if you're experiencing it still after going to 3.2, either re-open it or create a new issue please.

**Closed by AdamNaj** 2015-07-29 20:12 UTC
Labels: cannot-reproduce

**Comment by NDurham12** [comment] 2015-07-29 20:35
Hey there. Sorry I've been so busy. I did look at this yesterday but was
still having the issue.

Are there any warnings to upgrading from 3.0 to 3.1?

**Comment by AdamNaj** [comment] 2015-07-29 21:02
Not really, no. In the mean time I wouls check if anything in [this blog](http://blog.najmanowicz.com/2015/02/27/upgrading-your-sitecore-powershell-extensions-from-2-x-to-3-x-what-you-need-to-know/)  might help.
