### ISSUE TITLE
Question: how to expand timeout parameter for remote scripts?

### ISSUE THREAD

**Issue by Temaska** [SitecorePowerShell/Console#713] opened 2016-10-11 11:49 UTC
I read other issues related to timeout and all solutions were use -AsJob argument to avoid timeout problem.
But by some reasons I can't use remote scripts as jobs. So question: is any way to expand timeout settings for remote scripts? Currently it works only 2 minutes.

I assume it configured somewhere on the Sitecore side

Thanks

**Comment by michaellwest** [comment] 2016-10-12 14:58
Hi @Temaska. A few questions to better support you. What version of SPE are you using? What version of Windows PowerShell is installed on the machine? Running `$PSVersionTable` and `Get-Host` in Sitecore can help obtain that information.

Can you also provide a snippet of what your script looks like? That could help us reproduce the issue.

**Comment by Temaska** [comment] 2016-10-12 16:18
@michaellwest thank you for taking a look into the problem

SPE version is 4.1.0.3343
Windows Powershell version is 4.0

My script recursively goes through all items all version and languages and updates field. As we have big tree it takes about 6 minutes.
You can reproduce it by just calling
`Start-Sleep -m 3`
in your remote script

**Comment by michaellwest** [comment] 2016-10-13 03:52
@Temaska Have you checked out this page already? https://sitecorepowershell.gitbooks.io/sitecore-powershell-extensions/content/remoting.html

**Comment by michaellwest** [comment] 2016-10-23 20:10
Hey @Temaska you'll want to follow this example:

```powershell
Import-Module -Name SPE
$session = New-ScriptSession -Username admin -Password b -ConnectionUri http://remotesitecore
$jobId = Invoke-RemoteScript -Session $session -ScriptBlock {
        Start-Sleep -m 3
} -AsJob
Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 7 -Verbose
Stop-ScriptSession -Session $session
```

We have not had any other reports of this issue so we'll go ahead and close it for now. Please reopen and comment if you discover any new information.

**Closed by michaellwest** 2016-10-23 20:10 UTC

**Comment by Temaska** [comment] 2016-10-24 09:06
this example(as and other examples for long running scripts) uses -AsJob argument to solve timeout problem. Question was about how to expand timeout parameter, not how to avoid it

**Comment by michaellwest** [comment] 2016-10-24 22:35
The example I gave with using -AsJob returns immediately with a reference to the job. The wait command polls so there is no reason to experience a timeout.

The only way to increase the web service timeout is to increase the timeout for asmx services in the web.config.
