### ISSUE TITLE
Debugger not hitting breakpoints

### ISSUE THREAD

**Issue by kamsar** [SitecorePowerShell/Console#705] opened 2016-09-14 18:20 UTC
Not all people with 8.2 RTM seem to have this problem, but I do.

1. Open ISE
2. Enter a script, e.g. 
```
1..10 | % {
    Write-Host $_
}
```
3. Place a breakpoint (in my case on line 2)
4. Hit debug
5. The breakpoint is not hit and execution continues to completion

The following exception is in the SPE logs:
```
1368 09:58:12 INFO  Executing a script in ScriptSession '$scriptSession$|c5xqb3tad2dhry11agvasquz|ISE Editing Session'.
1368 09:58:12 WARN  Current context is not a jobAt line:1 char:1
+ Set-PSBreakpoint -Script C:\Web\legendary-pancake\website\temp\tmpA8D ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exception: Sitecore.Jobs.AsyncUI.InvalidContextException
Message: Current context is not a job
Source: Sitecore.Kernel
   at Sitecore.Jobs.AsyncUI.JobContext.get_Job()
   at Sitecore.Jobs.AsyncUI.SendMessageMessage..ctor(Message message, Boolean postBack)
   at Cognifide.PowerShell.Core.Host.ScriptSession.SendUiMessage(Message message)
   at Cognifide.PowerShell.Core.Host.ScriptSession.DebuggerOnBreakpointUpdated(Object sender, BreakpointUpdatedEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler`1 eventHandler, Object sender, T eventArgs)
   at System.Management.Automation.ScriptDebugger.AddBreakpointCommon(Breakpoint breakpoint)
   at Microsoft.PowerShell.Commands.SetPSBreakpointCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

This does NOT occur on a 8.1 Update-3 with the same package

**Comment by AlexKasaku** [comment] 2016-09-26 22:06
This will require some investigation, on my machine I've been unable to reproduce so far and mine hits the breakpoint.

@AdamNaj - Any ideas on this? It looks like `ScriptSession.SendUiMessage` has a flaw in that the `Sitecore.Jobs.AsyncUI.SendMessageMessage` class ctor will throw an exception if the current context is not a job, [so the following if/else statement](https://github.com/SitecorePowerShell/Console/blob/8b04a9e02a9238f64e7de1a1a25b74b759ff3d2a/Cognifide.PowerShell/Core/Host/ScriptSession.cs#L309-L317) will always be true by the time its reached. What I'm not sure of is what would lead to this code executing outside the context of a job.

**Comment by AdamNaj** [comment] 2016-10-12 16:34
The problem seems to be related with the setting of breakpoints rather than with jobs. The fact that the stack trace is showing JobContext being null is related to the fact that breakpoints setup happens before we dive into the job itself.

Kam - maybe any of the following will hint on why this is happening for you:
For the debugging to be possible PowerShell requires that the script being debugged needs to be saved to the drive and run from there. Is there anything particular in terms of rights/permissions that you have set up in the instance? e.g. the app pool not having some specific privileges to not be able to do something specific in the folder etc?

**Comment by kamsar** [comment] 2016-10-12 16:37
The app pool was running as `AppPoolIdentity` and the app pool user was granted `Modify` rights to the Sitecore web-root and data folder. It would probably not have rights to much else.

**Comment by kamsar** [comment] 2016-10-13 14:57
@AdamNaj provided me with an updated package, which seems to have solved the issue for me.

**Comment by AdamNaj** [comment] 2016-10-13 14:58
Great news! Marking as solved :)

**Closed by AdamNaj** 2016-10-13 14:58 UTC
Labels: area-debugging, area-development-ui, bug

**Comment by AlexKasaku** [comment] 2016-10-13 15:33
Great fix @AdamNaj!
